import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/');
  await expect(page.locator('div').nth(2)).toBeVisible();
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await expect(page.locator('#form')).toContainText('New User Signup!');
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('qa tester');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('qatester@email.com');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowLeft');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowLeft');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowLeft');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowLeft');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowLeft');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowLeft');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowRight');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').press('ArrowRight');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('qatester@email.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await expect(page.locator('#form')).toContainText('Enter Account Information');
  await page.getByRole('radio', { name: 'Mr.' }).check();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('qapassword');
  await page.locator('#days').selectOption('1');
  await page.locator('#months').selectOption('1');
  await page.locator('#years').selectOption('2000');
  await page.getByRole('textbox', { name: 'First name *' }).click();
  await page.getByRole('textbox', { name: 'First name *' }).fill('qa');
  await page.getByRole('textbox', { name: 'Last name *' }).click();
  await page.getByRole('textbox', { name: 'Last name *' }).fill('tester');
  await page.getByRole('textbox', { name: 'Company', exact: true }).click();
  await page.getByRole('textbox', { name: 'Company', exact: true }).fill('qa ');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).click();
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('qa office');
  await page.getByRole('textbox', { name: 'Address 2' }).click();
  await page.getByRole('textbox', { name: 'Address 2' }).fill('qa office 2');
  await page.getByLabel('Country *').selectOption('United States');
  await page.getByRole('textbox', { name: 'State *' }).click();
  await page.getByRole('textbox', { name: 'State *' }).fill('texas');
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).click();
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('texas');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('12345');
  await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('1234567890');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await expect(page.locator('b')).toContainText('Account Created!');
  await page.getByRole('link', { name: 'Continue' }).click();
  await expect(page.locator('#header')).toContainText('Logged in as qa tester');
});